export const products = [
    {
        name: 'Guantes GN102',
        price: 59.9,
        isAvailable: true,
        category: 'gloves',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Casco CS433',
        price: 79.9,
        isAvailable: true,
        category: 'headgear',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Bolsa AC990',
        price: 79.9,
        isAvailable: true,
        category: 'bags',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Botas BT245',
        price: 129.9,
        isAvailable: true,
        category: 'footwear',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Chaqueta JK887',
        price: 189.5,
        isAvailable: false,
        category: 'jackets',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Gafas GF334',
        price: 45.0,
        isAvailable: true,
        category: 'eyewear',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Pantalón PT556',
        price: 95.8,
        isAvailable: true,
        category: 'pants',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Mochila MC778',
        price: 159.9,
        isAvailable: true,
        category: 'bags',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Reloj RJ223',
        price: 299.0,
        isAvailable: false,
        category: 'accessories',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Camisa CM445',
        price: 67.5,
        isAvailable: true,
        category: 'shirts',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Cinturón CN112',
        price: 38.9,
        isAvailable: true,
        category: 'accessories',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Sudadera SD669',
        price: 78.0,
        isAvailable: true,
        category: 'sweatshirts',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Zapatillas ZP890',
        price: 149.9,
        isAvailable: false,
        category: 'footwear',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Bufanda BF123',
        price: 25.5,
        isAvailable: true,
        category: 'accessories',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Gorro GR456',
        price: 32.0,
        isAvailable: true,
        category: 'headgear',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Shorts SH789',
        price: 54.9,
        isAvailable: true,
        category: 'shorts',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Calcetines CL234',
        price: 12.5,
        isAvailable: true,
        category: 'socks',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Vestido VD567',
        price: 119.9,
        isAvailable: false,
        category: 'dresses',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Abrigo AB890',
        price: 259.0,
        isAvailable: true,
        category: 'coats',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Camiseta CT345',
        price: 29.9,
        isAvailable: true,
        category: 'shirts',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Falda FL678',
        price: 68.5,
        isAvailable: true,
        category: 'skirts',
        image: 'https://picsum.photos/200/200',
    },
    {
        name: 'Collar CL901',
        price: 85.0,
        isAvailable: false,
        category: 'accessories',
        image: 'https://picsum.photos/200/200',
    },
]